ferbot:
  wit:
    minConfidence: 0.5
    url: https://api.wit.ai/message
    access_token: xxx
  facebook:
    verification: xxx
    secret: xxx
    page:
      access_token: xxx
    messenger:
      url: https://graph.facebook.com/v2.6/me/messages